### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Physiix** [Physiix/topsi-project-manager#1]
- Quick commands
- Better image attachment (currently slows down the application)
- Comments
- Support for other languages than English. (Translation)
- Plugin system
- Better milestone management
- File attachments
- Undo / Redo
- Synchronize with github and gitlab issues: 
	- Import issues from github/gitlab
	- Local changes are 
- Refactoring
- Users
- Updates

**Comment by superlbr** [comment]
need deadline(date alert) in tasks

**Comment by superlbr** [comment]
support copy & paste
