### ISSUE TITLE
How run in cetnos7?

### ISSUE THREAD

**Issue by shangdev** [Physiix/topsi-project-manager#10]
I downloaded the installation package, then run:
```
# yarn
# yarn run dev
# yarn build
```
But how can I access this application on the web?Please help me.

**Comment by Physiix** [comment]
I didn't try the application on CentOS, but you can download `topsi-linux-x86_64.AppImage` from the release page https://github.com/Physiix/topsi-project-manager/releases and try it.
Topsi is a desktop application though.

**Comment by shangdev** [comment]
I did not try to succeed
This may not work in CentOS, please close this question,thanks.
