### ISSUE TITLE
Cannot create a note ...

### ISSUE THREAD

**Issue by zouqian2468** [Physiix/topsi-project-manager#15]
Cannot create a note with invalid data [object Object]

**Comment by MikkelPorse** [comment]
I came across this as well. It seems to be a bug in the state-management, where $state.getCurrentMilestoneId returns undefined. In my case this happened when I added another lane to the interface and the project was reloaded.

 Work-around: open milestones, and select current milestoneId.

**Comment by Physiix** [comment]
Better error reporting is being worked on :)

**Comment by androidovshchik** [comment]
@zouqian2468 Choose one of available milestones. it works for me
