### ISSUE TITLE
Creating new Milestone - first id is 0, should be 1

### ISSUE THREAD

**Issue by MikkelPorse** [Physiix/topsi-project-manager#18]
database.json
the property "milestones_id" contains the id of the next milestone to be created, but in a new project it is initialized to 0 - which is the default milestone. So, when you create a new milestone, it will also have id=0.

Solution: set "milestone_id" = 1 in a new project.

**Comment by Physiix** [comment]
It's already been fixed in 7fdddb9b19927f7045bc940264be7d5af76055d6
