### ISSUE TITLE
Newly created projects are not reactively added to the landing page

### ISSUE THREAD

**Issue by dreamski21** [Physiix/topsi-project-manager#43]
**OS:** Ubuntu 18.04.2 x64

**Commit:** `df8604994789941d1ee3140e397cf11347582ef2` (Date: Sat Jun 1 09:30:44 2019 -0400)

**How to reproduce:**
- cd to the project's folder
- Run `npm run dev`
- Click "New project" and fill in a name then finish.
- Only a success message appears.

**Expected:** The newly created project will be appended automatically.

**Actual:** Nothing happens: You need to open one of the already created projects then go back so that the new project appears.

![Screenshot from 2019-06-04 01-13-24](https://user-images.githubusercontent.com/32184973/58843097-fbc19780-8668-11e9-8cdd-f316f3534401.png)

**Comment by Physiix** [comment]
Thanks for reporting the issue. 
It should be fixed with the last commit. 
Let me know if it works for you if you test it !

**Comment by dreamski21** [comment]
Tested. It works correctly now.
Thanks for the quick response.
