### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by forhonourlx** [Physiix/topsi-project-manager#5]
Hi,

Could somebody give me a hand how to build on windows?
Thank you for your help.

**Comment by alexdevero** [comment]
Hi @forhonourlx have you tried `npm run build` or `npm run build:dir`?

**Comment by yangli8953** [comment]
I have got following message!@alexdevero
C:\Users\thinkpad\topsi-project-manager>npm run build

> topsi_project_manager@0.0.0 build C:\Users\thinkpad\topsi-project-manager
> node .electron-vue/build.js && electron-builder

module.js:549
    throw err;
    ^

Error: Cannot find module 'cfonts'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\thinkpad\topsi-project-manager\.electron-vue\build.js:5:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! topsi_project_manager@0.0.0 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the topsi_project_manager@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thinkpad\AppData\Roaming\npm-cache\_logs\2018-08-28T10_00_00_006Z-debug.log

**Comment by alexdevero** [comment]
@yangli8953 followup question. Did you first ran `npm install` or `yarn`, after you cloned/forked/downloaded the repo?

**Comment by yangli8953** [comment]
I have passed the error and saw the main interface,but what does "Cannot create a note with invalid data[object Object] mean?

**Comment by sdhutchins** [comment]
I just had the same issue and your instructions resolved it @alexdevero. Would this be something worth adding to the readme for a newb like myself? :laughing:

**Comment by Physiix** [comment]
It's already in the README.md file https://github.com/Physiix/topsi-project-manager/blob/master/README.md#build lol

**Comment by sdhutchins** [comment]
@Physiix not the npm version...and not that it should be if a person has used npm but...haha

**Comment by Physiix** [comment]
You may be right, you can add `npm install` in the comments and create a PR if you want
